
include $(GNUSTEP_MAKEFILES)/common.make

#GNUSTEP_MAKEINFO_FLAGS = -D NO-TEXI2HTML

DOCUMENT_NAME = manual

manual_TEXI_FILES =              \
	manual.texi              \
	Introduction.texi        \
	BasicClasses.texi

manual_DOC_INSTALL_DIR = Developer/Gui/ProgrammingManual

include $(GNUSTEP_MAKEFILES)/documentation.make


