after-distclean::
	rm -f GNUmakefile.local

$(GNUSTEP_INSTALLATION_DIR)/Library/Model:
	$(MKDIRS) $(GNUSTEP_INSTALLATION_DIR)/Library/Model

before-install:: $(GNUSTEP_INSTALLATION_DIR)/Library/Model
	for f in $(PANELS); do \
	  $(INSTALL_DATA) $$f $(GNUSTEP_INSTALLATION_DIR)/Library/Model/; \
	done

before-uninstall::
	for f in $(PANELS); do \
		rm -f $(GNUSTEP_INSTALLATION_DIR)/Library/Model/$$f; \
	done

clean::

