# Simple Makefile for TouchBarExample

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = TouchBarExample
TouchBarExample_OBJC_FILES = TouchBarExample.m

include $(GNUSTEP_MAKEFILES)/application.make