include $(GNUSTEP_SYSTEM_ROOT)/Makefiles/common.make

# The application to be compiled
TOOL_NAME = testpb

# The source files to be compiled
testpb_OBJC_FILES = testpb.m

-include GNUmakefile.preamble

include $(GNUSTEP_SYSTEM_ROOT)/Makefiles/tool.make

-include GNUmakefile.postamble
