#
# Top-level base testsuite makefile
#
# Run this before loading any tests
#

include $(GNUSTEP_MAKEFILES)/common.make

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/rules.make

-include GNUmakefile.postamble
