#
#  Images makefile for GNUstep GUI Library
#  Copyright (C) 1997 Free Software Foundation, Inc.
#
#  Author:  Scott Christley <scottc@net-community.com>
#  Date:  September 1997
#
#  This file is part of the GNUstep GUI Library.
#
#  This library is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation; either
#  version 2 of the License, or (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the GNU
#  Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public
#  License along with this library; see the file COPYING.LIB.
#  If not, see <http://www.gnu.org/licenses/> or write to the 
#  Free Software Foundation, 51 Franklin Street, Fifth Floor, 
#  Boston, MA 02110-1301, USA.

GNUSTEP_INSTALLATION_DOMAIN = SYSTEM

GNUSTEP_LOCAL_ADDITIONAL_MAKEFILES=../gui.make
include $(GNUSTEP_MAKEFILES)/common.make

include ../Version

imagedir = $(GNUSTEP_LIBRARY)/Images

IMAGE_FILES = \
LogoGNUstep.tiff \
common_3DArrowUp.tiff \
common_3DArrowLeft.tiff \
common_3DArrowDown.tiff \
common_ArrowDown.tiff \
common_ArrowDownH.tiff \
common_ArrowUp.tiff \
common_ArrowUpH.tiff \
common_ArrowRight.tiff \
common_ArrowRightH.tiff \
common_3DArrowRight.tiff \
common_ArrowLeft.tiff \
common_ArrowLeftH.tiff \
common_3DArrowRightH.tiff \
common_2DCheckMark.tiff \
common_Close.tiff \
common_CloseH.tiff \
common_CloseBroken.tiff \
common_CloseBrokenH.tiff \
common_ColorSwatch.tiff \
common_2DDash.tiff \
common_HelpCursor.tiff \
common_Home.tiff \
common_HomeDirectory.tiff \
common_Mount.tiff \
common_Miniaturize.tiff \
common_MiniaturizeH.tiff \
common_MiniWindowTile.tiff \
common_Unmount.tiff \
common_RadioOn.tiff \
common_RadioOff.tiff \
common_Right.tiff \
common_RightH.tiff \
common_SwitchOn.tiff \
common_SwitchOff.tiff \
common_SliderHoriz.tiff \
common_SliderVert.tiff \
common_TabDownSelectedLeft.tiff \
common_TabDownSelectedRight.tiff \
common_TabDownSelectedToUnSelectedJunction.tiff \
common_TabDownUnSelectedJunction.tiff \
common_TabDownUnSelectedLeft.tiff \
common_TabDownUnSelectedRight.tiff \
common_TabDownUnSelectedToSelectedJunction.tiff \
common_TabSelectedLeft.tiff \
common_TabSelectedRight.tiff \
common_TabSelectedToUnSelectedJunction.tiff \
common_TabUnSelectToSelectedJunction.tiff \
common_TabUnSelectedJunction.tiff \
common_TabUnSelectedLeft.tiff \
common_TabUnSelectedRight.tiff \
common_Tile.tiff \
common_UpAndDownArrowSmall.tiff \
common_DownArrowSmall.tiff \
common_Nibble.tiff \
common_Dimple.tiff \
common_ret.tiff \
common_retH.tiff \
common_Unknown.tiff \
common_UnknownApplication.tiff \
common_UnknownTool.tiff \
common_Folder.tiff \
common_Root_PC.tiff \
common_Root_SGI.tiff \
common_Root_Sparc.tiff \
common_Root_Sparc2.tiff \
common_Root_Apple.tiff \
common_noCursor.tiff \
common_copyCursor.tiff \
common_linkCursor.tiff \
common_outlineCollapsed.tiff \
common_outlineExpanded.tiff \
common_outlineUnexpandable.tiff \
GNUstep.tiff \
GNUstepMenuImage.tiff \
nsmapping.strings \
NSComboArrow.tiff \
common_ComboBoxEllipsis.tiff \
common_RightTabStop.tiff \
common_CenterTabStop.tiff \
common_LeftTabStop.tiff \
common_DecimalTabStop.tiff \
common_Diamond.tiff \
common_Printer.tiff \
common_ToolbarClippedItemsMark.tiff \
common_ToolbarSeparatorItem.tiff \
common_ToolbarShowColorsItem.tiff \
common_ToolbarShowFontsItem.tiff \
common_ToolbarSpaceItem.tiff \
common_ClosedHandCursor.tiff \
common_OpenHandCursor.tiff \
page_landscape.tiff \
page_portrait.tiff \
MagnifyGlass.tiff \
GSSearch.tiff \
GSStop.tiff \
NSRatingLevelIndicator.tiff

-include GNUmakefile.preamble

-include GNUmakefile.local
# We don't actually build anything in this directory so
# just include the common makefile rules
include $(GNUSTEP_MAKEFILES)/rules.make

include GNUmakefile.postamble
