#
#  Images makefile for GNUstep GUI Library
#  Copyright (C) 1997 Free Software Foundation, Inc.
#
#  Author:  Scott Christley <scottc@net-community.com>
#  Date:  September 1997
#
#  This file is part of the GNUstep GUI Library.
#
#  This library is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Library General Public
#  License as published by the Free Software Foundation; either
#  version 2 of the License, or (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the GNU
#  Library General Public License for more details.
#
#  You should have received a copy of the GNU Library General Public
#  License along with this library; if not, write to the Free
#  Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111 USA.

GNUSTEP_INSTALLATION_DIR = $(GNUSTEP_SYSTEM_ROOT)

GNUSTEP_MAKEFILES = $(GNUSTEP_SYSTEM_ROOT)/Makefiles

include $(GNUSTEP_MAKEFILES)/common.make

include ../Version

imagedir = $(GNUSTEP_RESOURCES)/Images

IMAGE_FILES = \
GNUstep_Images_Copyright \
common_3DArrowDown.tiff \
common_ArrowDown.tiff \
common_ArrowUp.tiff \
common_ArrowRight.tiff \
common_3DArrowRight.tiff \
common_ArrowLeft.tiff \
common_ArrowDownH.tiff \
common_ArrowUpH.tiff \
common_ArrowRightH.tiff \
common_3DArrowRightH.tiff \
common_ArrowLeftH.tiff \
common_2DCheckMark.tiff \
common_Close.tiff \
common_CloseH.tiff \
common_CloseBroken.tiff \
common_ColorSwatch.tiff \
common_2DDash.tiff \
common_Home.tiff \
common_Mount.tiff \
common_Unmount.tiff \
common_RadioOn.tiff \
common_RadioOff.tiff \
common_Right.tiff \
common_RightH.tiff \
common_SwitchOn.tiff \
common_SwitchOff.tiff \
common_SliderHoriz.tiff \
common_SliderVert.tiff \
common_TabDownSelectedLeft.tiff \
common_TabDownSelectedRight.tiff \
common_TabDownSelectedToUnSelectedJunction.tiff \
common_TabDownUnSelectedJunction.tiff \
common_TabDownUnSelectedLeft.tiff \
common_TabDownUnSelectedRight.tiff \
common_TabDownUnSelectedToSelectedJunction.tiff \
common_TabSelectedLeft.tiff \
common_TabSelectedRight.tiff \
common_TabSelectedToUnSelectedJunction.tiff \
common_TabUnSelectToSelectedJunction.tiff \
common_TabUnSelectedJunction.tiff \
common_TabUnSelectedLeft.tiff \
common_TabUnSelectedRight.tiff \
common_Tile.tiff \
common_UpAndDownArrowSmall.tiff \
common_DownArrowSmall.tiff \
common_Nibble.tiff \
common_Dimple.tiff \
common_ret.tiff \
common_retH.tiff \
common_WMClose.tiff \
common_WMCloseBroken.tiff \
common_Unknown.tiff \
common_Folder.tiff \
common_Root_PC.tiff \
common_Root_SGI.tiff \
common_Root_Sparc.tiff \
common_Root_Sparc2.tiff \
common_Root_Apple.tiff \
GNUstep.tiff \
GNUstepMenuImage.tiff \
nsmapping.strings \
NSComboArrow.tiff \
common_Diamond.tiff

-include GNUmakefile.preamble

-include GNUmakefile.local
# We don't actually build anything in this directory so
# just include the common makefile rules
include $(GNUSTEP_MAKEFILES)/rules.make

-include GNUmakefile.postamble
