#
#  Images makefile for GNUstep GUI Library
#  Copyright (C) 1997 Free Software Foundation, Inc.
#
#  Author:  Scott Christley <scottc@net-community.com>
#  Date:  September 1997
#
#  This file is part of the GNUstep GUI Library.
#
#  This library is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Library General Public
#  License as published by the Free Software Foundation; either
#  version 2 of the License, or (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the GNU
#  Library General Public License for more details.
#
#  You should have received a copy of the GNU Library General Public
#  License along with this library; if not, write to the Free
#  Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

include $(GNUSTEP_SYSTEM_ROOT)/Makefiles/common.make

include ../Version

imagedir = $(GNUSTEP_RESOURCES)/Images

IMAGE_FILES = \
GNUstep_Images_Copyright \
common_ArrowDown.tiff \
common_ArrowUp.tiff \
common_ArrowRight.tiff \
common_ArrowLeft.tiff \
common_ArrowDownH.tiff \
common_ArrowUpH.tiff \
common_ArrowRightH.tiff \
common_ArrowLeftH.tiff \
common_Close.tiff \
common_CloseH.tiff \
common_CloseBroken.tiff \
common_RadioOn.tiff \
common_RadioOff.tiff \
common_Right.tiff \
common_RightH.tiff \
common_SwitchOn.tiff \
common_SwitchOff.tiff \
common_SliderHoriz.tiff \
common_SliderVert.tiff \
common_Dimple.tiff \
common_ret.tiff

-include Makefile.preamble

# We don't actually build anything in this directory so
# just include the common makefile rules
include $(GNUSTEP_SYSTEM_ROOT)/Makefiles/rules.make

-include Makefile.postamble
