#
#   Makefile.postamble
#
#   Project specific makefile rules
#
#   Copyright (C) 2005 Free Software Foundation, Inc.
#
#   Uncomment the targets you want.
#   The double colons (::) are important, do not make them single colons
#   otherwise the normal makefile rules will not be performed.
#

# Things to do before compiling
# before-all::

# Things to do after compiling
# after-all::

# Things to do before installing
# before-install::

# Things to do after installing
# GSspell is built for the target, so it cannot be run here when cross
# compiling.  GNUmakefile guards make_services the same way.
after-install::
ifneq ($(CROSS_COMPILING),yes)
	GSspell.service/GSspell -RegisterOnly YES
endif

# Things to do before uninstalling
# before-uninstall::

# Things to do after uninstalling
# after-uninstall::

# Things to do before cleaning
# before-clean::

# Things to do after cleaning
# after-clean::

# Things to do before distcleaning
# before-distclean::

# Things to do after distcleaning
# after-distclean::

# Things to do before checking
# before-check::

# Things to do after checking
# after-check::
