include $(GNUSTEP_SYSTEM_ROOT)/Makefiles/common.make

# The application to be compiled
TOOL_NAME = gpbs

# The source files to be compiled
gpbs_OBJC_FILES = gpbs.m

-include Makefile.preamble

include $(GNUSTEP_SYSTEM_ROOT)/Makefiles/tool.make

-include Makefile.postamble
